
## Start - Inserted by CoreOS-Vagrant Cluster GUI App

      # Change core-01 host ssh port forward to 2322, so that will not clash with other vagrant VM using 2222
      config.vm.network "forwarded_port", guest: 22, host: 2322, id: "ssh", auto_correct: true

## End - Inserted by CoreOS-Vagrant Cluster GUI App
